build:
	@gcc -std=gnu99 main.c vga_driver.c driver.s -o validador -lrt -lm

run:
	sudo ./exe

help:
	@echo ""
	@echo "📘 Comandos disponíveis:"
	@echo "  make build   - Compila o programa (gera exe)"
	@echo "  make run     - Executa o programa (usa sudo)"
	@echo "  make help    - Mostra esta mensagem de ajuda"
	@echo ""